### ISSUE TITLE
[master/fusejs branch] installation

### ISSUE THREAD

**Issue by karbowiak** [thejinx0r/node-gdrive-fuse#30]
Hi, i decide to try and help trackdown bugs in the fusejs branch.
But i hit a roadblock in even installing it, lol.
1. During building the modules it whined about ck, i downloaded, built and installed http://concurrencykit.org/ and the whine went away
2. fusejs refuses to build, full install log as follows

```
$ npm install

> fusejs@0.0.2 install /opt/gdrivejs/node_modules/fusejs
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/opt/gdrivejs/node_modules/fusejs/build'
  CXX(target) Release/obj.target/fusejs/src/bindings.o
  CXX(target) Release/obj.target/fusejs/src/file_info.o
../src/file_info.cc: In static member function ‘static void NodeFuse::FileInfo::Initialize()’:
../src/file_info.cc:60:30: error: ‘shlock_sym’ was not declared in this scope
         NanAssignPersistent( shlock_sym    , NanNew("shlock"));
                              ^
../src/file_info.cc:61:30: error: ‘exlock_sym’ was not declared in this scope
         NanAssignPersistent( exlock_sym    , NanNew("exlock"));
                              ^
../src/file_info.cc:63:30: error: ‘symlink_sym’ was not declared in this scope
         NanAssignPersistent( symlink_sym   , NanNew("symlink"));
                              ^
../src/file_info.cc:64:30: error: ‘evtonly_sym’ was not declared in this scope
         NanAssignPersistent( evtonly_sym   , NanNew("evtonly"));
                              ^
../src/file_info.cc: In static member function ‘static void NodeFuse::FileInfo::SetNonSeekable(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’:
../src/file_info.cc:250:19: warning: unused variable ‘fileInfo’ [-Wunused-variable]
         FileInfo *fileInfo = ObjectWrap::Unwrap<FileInfo>(args.This());
                   ^
make: *** [Release/obj.target/fusejs/src/file_info.o] Error 1
make: Leaving directory `/opt/gdrivejs/node_modules/fusejs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 3.16.6-kk4
gyp ERR! command "node" "/root/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/gdrivejs/node_modules/fusejs
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> mmmagic@0.3.12 install /opt/gdrivejs/node_modules/mmmagic
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/opt/gdrivejs/node_modules/mmmagic/build'
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
../deps/libmagic/src/cdf.c: In function ‘cdf_read’:
../deps/libmagic/src/cdf.c:303:2: warning: implicit declaration of function ‘pread’ [-Wimplicit-function-declaration]
  if (pread(info->i_fd, buf, len, off) != (ssize_t)len)
  ^
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/encoding.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fsmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/funcs.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/is_tar.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/magic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/print.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readcdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readelf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/softmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fmtcheck.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcat.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcpy.o
  AR(target) Release/obj.target/deps/libmagic/magic.a
  COPY Release/magic.a
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_byte_order.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_chartables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_compile.o
../deps/libmagic/pcre/pcre_compile.c: In function ‘add_to_class’:
../deps/libmagic/pcre/pcre_compile.c:3479:28: warning: ‘od’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       else if (oc >= start && od <= end) continue;
                            ^
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_config.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_dfa_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_fullinfo.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_get.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_globals.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_jit_compile.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_maketables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_newline.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ord2utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_refcount.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_string_utils.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_study.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_tables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ucd.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_valid_utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_version.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_xclass.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcreposix.o
  AR(target) Release/obj.target/deps/libmagic/pcre/pcre.a
  COPY Release/pcre.a
  CXX(target) Release/obj.target/magic/src/magic.o
  SOLINK_MODULE(target) Release/obj.target/magic.node
  SOLINK_MODULE(target) Release/obj.target/magic.node: Finished
  COPY Release/magic.node
make: Leaving directory `/opt/gdrivejs/node_modules/mmmagic/build'
npm ERR! Linux 3.16.6-kk4
npm ERR! argv "/root/.nvm/v0.11.14/bin/node" "/root/.nvm/v0.11.14/bin/npm" "install"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE

npm ERR! fusejs@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fusejs@0.0.2 install script.
npm ERR! This is most likely a problem with the fusejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fusejs
npm ERR! There is likely additional logging output above.
```

I run node 0.11.14 installed via nvm, no idea if that has anything to do with it :)

**Comment by robot2xl** [comment]
npm ERR! fusejs@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fusejs@0.0.2 install script.
npm ERR! This is most likely a problem with the fusejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fusejs
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "/Users/private/.nvm/v0.10.25/bin/node" "/Users/private/.nvm/v0.10.25/bin/npm" "install"
npm ERR! cwd /Users/private/node-gdrive-fuse
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/snow/node-gdrive-fuse/npm-debug.log
npm ERR! not ok code 0
