### ISSUE TITLE
[Error] Cannot read property 'cache' of undefined

### ISSUE THREAD

**Issue by karbowiak** [thejinx0r/node-gdrive-fuse#33]
Error is as follows:
```
/opt/gdrivejs/src/fs.coffee:686
      uploadedFileLocation = pth.join(uploadLocation, uploadedFile.cache);
                                                                  ^
TypeError: Cannot read property 'cache' of undefined
  at /opt/gdrivejs/src/fs.coffee:671:65
  at cbUploadData (/opt/gdrivejs/src/folder.coffee:414:19)
  at Request.requestCallback [as _callback] (/opt/gdrivejs/src/folder.coffee:213:7)
  at Request.self.callback (/opt/gdrivejs/node_modules/request/request.js:373:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/opt/gdrivejs/node_modules/request/request.js:1318:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/opt/gdrivejs/node_modules/request/request.js:1266:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:372:11)
```

**Comment by karbowiak** [comment]
Havn't had this issue for the past, oh, 8 hours, so it's more than likely fixed! :)
