### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by ecchi** [thejinx0r/node-gdrive-fuse#37]
Pulled latest latest commit bad68d59d4

I've deleted cache from previous versions. Turned on debug to see if that helps at all (doesn't):

```
Access Token Set
2014-12-31T13:48::26 - info: Loading folder structure
2014-12-31T13:48::27 - debug: Getting changes from Google Drive. The last change id was 248982.
2014-12-31T13:48::27 - info: attempting to start f4js
2014-12-31T13:48::27 - info: unmounting output: Unmount successful for /Users/ecchi/tmp/mnt

2014-12-31T13:48::27 - info: mount point: /Users/ecchi/tmp/mnt
2014-12-31T13:48::27 - debug: There was 1 to parse

TypeError: Cannot read property 'id' of undefined
  at parseChanges (/Users/ecchi/Code/node-gdrive-fuse/src/client.coffee:334:34)
  at callback (/Users/ecchi/Code/node-gdrive-fuse/src/client.coffee:281:7)
  at /Users/ecchi/Code/node-gdrive-fuse/src/client.coffee:262:7
  at Request._callback (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/lib/transporters.js:90:7)
  at Request.self.callback (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:372:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1317:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/ecchi/Code/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1265:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:442:13)
```

**Comment by thejinx0r** [comment]
I can't reproduce, but I put a bandaid fix for now.
