### ISSUE TITLE
fusejs build fails on yosemite 10.10.2

### ISSUE THREAD

**Issue by twayz** [thejinx0r/node-gdrive-fuse#45]
Hey,

I'm having an issue building fusejs when trying to install node-gdrive-fuse on osx 10.10.2
node version v0.11.14
npm 2.2.0
osxfuse 2.7.4

i tried node v0.10.35 and also osxfuse 2.7.3 but it still results in the same error below.

Thank you!

```
$ npm install

> fusejs@0.0.2 install /Users/julian/node-gdrive-fuse/node_modules/fusejs
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fusejs/src/bindings.o
  CXX(target) Release/obj.target/fusejs/src/file_info.o
../src/file_info.cc:258:19: warning: unused variable 'fileInfo' [-Wunused-variable]
        FileInfo *fileInfo = ObjectWrap::Unwrap<FileInfo>(args.This());
                  ^
In file included from ../src/file_info.cc:5:
In file included from ../src/file_info.h:4:
In file included from ../src/node_fuse.h:10:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:184:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/file_info.cc:282:24: note: in instantiation of function template specialization 'NanNew<v8::Integer, unsigned long long>' requested here
        NanReturnValue(NanNew<Integer>(fileInfo->fi->fh));
                       ^
../node_modules/nan/nan.h:231:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../node_modules/nan/nan_new.h:86:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:87:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
1 warning and 1 error generated.
make: *** [Release/obj.target/fusejs/src/file_info.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/julian/.anyenv/envs/ndenv/versions/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/julian/.anyenv/envs/ndenv/versions/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/julian/node-gdrive-fuse/node_modules/fusejs
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN deprecated tap-consumer@0.0.1: this is merged into the 'tap' module now
npm WARN deprecated tap-results@0.0.2: this is merged into the 'tap' module now

> mmmagic@0.3.12 install /Users/julian/node-gdrive-fuse/node_modules/mmmagic
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
../deps/libmagic/src/cdf.c:303:6: warning: implicit declaration of function 'pread' is invalid in C99 [-Wimplicit-function-declaration]
        if (pread(info->i_fd, buf, len, off) != (ssize_t)len)
            ^
1 warning generated.
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/encoding.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fsmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/funcs.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/is_tar.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/magic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/print.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readcdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readelf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/softmagic.o
  LIBTOOL-STATIC Release/magic.a
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_byte_order.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_chartables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_compile.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_config.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_dfa_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_exec.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_fullinfo.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_get.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_globals.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_jit_compile.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_maketables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_newline.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ord2utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_refcount.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_string_utils.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_study.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_tables.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_ucd.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_valid_utf8.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_version.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcre_xclass.o
  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcreposix.o
  LIBTOOL-STATIC Release/pcre.a
  CXX(target) Release/obj.target/magic/src/magic.o
../src/magic.cc:114:10: warning: private field 'error' is not used [-Wunused-private-field]
    bool error;
         ^
../src/magic.cc:115:10: warning: private field 'free_error' is not used [-Wunused-private-field]
    bool free_error;
         ^
../src/magic.cc:116:11: warning: private field 'error_message' is not used [-Wunused-private-field]
    char* error_message;
          ^
3 warnings generated.
  SOLINK_MODULE(target) Release/magic.node
  SOLINK_MODULE(target) Release/magic.node: Finished
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/julian/.anyenv/envs/ndenv/versions/v0.11.14/bin/npm" "install"
npm ERR! node v0.11.14
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE

npm ERR! fusejs@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fusejs@0.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fusejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fusejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/julian/node-gdrive-fuse/npm-debug.log
```

**Comment by thejinx0r** [comment]
There were a few bugs introduced in the newest version of NaN. If you try to reinstall it, it should work now.
