### ISSUE TITLE
assertion - TLSSocket.socketOnData

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#53]
latest commit get this error.

error
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: null == true
  at TLSSocket.socketOnData (_http_client.js:308:3)
  at TLSSocket.emit (events.js:107:17)
  at TLSSocket.Readable.read (_stream_readable.js:373:10)
  at TLSSocket.socketCloseListener (_http_client.js:229:10)
  at TLSSocket.emit (events.js:129:20)
  at TCP.close (net.js:476:12)

**Comment by thejinx0r** [comment]
might be related #57
