### ISSUE TITLE
access token null - crash

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#56]
crash with this log..

2015-5-17T16:34::34 - info: adding a new file sonarr_write_test.txt to folder TVShows
{ size: 0 }
/mnt/2TB3/sources/node-gdrive-fuse/src/file.coffee:109
          "Authorization": "Bearer " + config.accessToken.access_token,
                                                         ^
TypeError: Cannot read property 'access_token' of null
  at Function.GFile.download (/mnt/2TB3/sources/node-gdrive-fuse/src/file.coffee:68:54)
  at fn (/mnt/2TB3/sources/node-gdrive-fuse/src/file.coffee:324:21)
  at /mnt/2TB3/sources/node-gdrive-fuse/src/file.coffee:304:9
  at /mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/lib/auth/oauth2client.js:195:7
  at /mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/lib/auth/oauth2client.js:176:7
  at Request._callback (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/lib/transporters.js:97:7)
  at Request.self.callback (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:373:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:169:7)
  at Request.<anonymous> (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1318:14)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:166:7)
  at IncomingMessage.<anonymous> (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1266:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at endReadableNT (_stream_readable.js:890:12)
  at process._tickCallback (node.js:343:24)

**Comment by thejinx0r** [comment]
Is it reproducible?

**Comment by saqebakhter** [comment]
Not sure if its reproducible !

thejinx0r wrote:
> Saqeb Akhter

-- 
--Saqeb
