### ISSUE TITLE
parentid undefined

### ISSUE THREAD

**Issue by saqebakhter** [thejinx0r/node-gdrive-fuse#63]
get the following error on latest commit today:

/mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:407
          parent = inodeTree.get(obj.parentid);
                                    ^
TypeError: Cannot read property 'parentid' of undefined
  at parseChanges (/mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:386:35)
  at callback (/mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:363:7)
  at /mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:344:7
  at Request._callback (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/lib/transporters.js:97:7)
  at Request.self.callback (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:373:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:169:7)
  at Request.<anonymous> (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1318:14)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:166:7)
  at IncomingMessage.<anonymous> (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1266:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at endReadableNT (_stream_readable.js:890:12)
  at doNTCallback2 (node.js:437:9)
  at process._tickCallback (node.js:351:17)

**Comment by saqebakhter** [comment]
Just happened again:

2015-6-24T14:54::16 - info: adding a new file Footloose (2011).mkv to folder Footloose (2011)
2015-6-24T14:55::31 - info:  was renamed to New Folder
/mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:407
          parent = inodeTree.get(obj.parentid);
                                    ^
TypeError: Cannot read property 'parentid' of undefined
  at parseChanges (/mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:386:35)
  at callback (/mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:363:7)
  at /mnt/2TB3/sources/node-gdrive-fuse/src/client.coffee:344:7
  at Request._callback (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/lib/transporters.js:97:7)
  at Request.self.callback (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:373:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:169:7)
  at Request.<anonymous> (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1318:14)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:166:7)
  at IncomingMessage.<anonymous> (/mnt/2TB3/sources/node-gdrive-fuse/node_modules/googleapis/node_modules/request/request.js:1266:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at endReadableNT (_stream_readable.js:890:12)
  at doNTCallback2 (node.js:437:9)
  at process._tickCallback (node.js:351:17

**Comment by thejinx0r** [comment]
somehow, your inodeTree.json file got corrupted.
Can you try deleting it and have it redownload your folder structure from google?

**Comment by saqebakhter** [comment]
I do that everytime it crashes :S so it has a fresh inodeTree.


thejinx0r wrote:
>
> somehow, your inodeTree.json file got corrupted.
> Can you try deleting it and have it redownload your folder structure 
> from google?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/63#issuecomment-115041551>.
>

-- 
--Saqeb

**Comment by thejinx0r** [comment]
I'm going to be away for a couple of weeks. I may not have time to investigate. 
If I do, can I still log in to your vps to check it out?

**Comment by saqebakhter** [comment]
I actually do all my uploading from my home server - I can share that 
setup with you. I'll email it to you.

thejinx0r wrote:
>
> I'm going to be away for a couple of weeks. I may not have time to 
> investigate.
> If I do, can I still log in to your vps to check it out?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thejinx0r/node-gdrive-fuse/issues/63#issuecomment-115406691>.
>

-- 
--Saqeb

**Comment by thejinx0r** [comment]
Closing for now.
If this problem is reproducible in the new version, please reopen.
