### ISSUE TITLE
node-gdrive-fuse crashes during large uploads

### ISSUE THREAD

**Issue by dellipse** [thejinx0r/node-gdrive-fuse#67]
When resuming the uploading of files, the following error is displayed via debug only:

TypeError: Cannot read property 'title' of undefined
  at parseChanges (/home/install/node-gdrive-fuse/src/client.coffee:379:31)
  at callback (/home/install/node-gdrive-fuse/src/client.coffee:363:7)
  at /home/install/node-gdrive-fuse/src/client.coffee:344:7
  at Request._callback (/home/install/node-gdrive-fuse/node_modules/googleapis/lib/tran
  at Request.self.callback (/home/install/node-gdrive-fuse/node_modules/googleapis/node
  at Request.EventEmitter.emit (events.js:98:17)
  at Request.<anonymous> (/home/install/node-gdrive-fuse/node_modules/googleapis/node_m
  at Request.EventEmitter.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/home/install/node-gdrive-fuse/node_modules/googleapi
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:920:16
  at process._tickCallback (node.js:415:13)

This might also be related to #64 as well

**Comment by thejinx0r** [comment]
Yes, it's the same error. It's related to parsing changes and not to file uploading.
