### ISSUE TITLE
Ubuntu Server 15.10 - SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by ecchi** [thejinx0r/node-gdrive-fuse#88]
Followed directions for installing on ubuntu. Obviously my fault for using unsupported 10.15 version, but thought it might be of some importance. Mainly did the test, to see if my problems on Mac were unique to my account or not, or if it was the OS. Will attempt LTS another day. Its late here.

```
node client.es6.js 

/home/ecchi/node-gdrive-fuse/src/client.es6.js:2
const readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

```
node fs.es6.js 

/home/ecchi/node-gdrive-fuse/src/fs.es6.js:2
const google = require( 'googleapis' );
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by thejinx0r** [comment]
I should update those instructions as I didn't write those, but I would suggest to use nvm and install a newer version of nodejs.

**Comment by dellipse** [comment]
I am also having the same issues with the latest version of node.js (5.0.0)

As of today, what version are you coding against?
