### ISSUE TITLE
key reply:  false

### ISSUE THREAD

**Issue by wnielson** [thejinx0r/node-gdrive-fuse#92]
I've been seeing this happen a lot in the logs:
```
2016-1-13T22:24::18 - info: key reply:  false
Trace
    at null._repeat (/opt/node-gdrive-fuse-3/src/fs.es6.js:868:25)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
   unique: 139770650951800, success, outsize: 66526
2016-1-13T22:24::18 - debug: retrying read
```
Occasionally it appears to cause the program to hang as well.

**Comment by cal2195** [comment]
This happened earlier to me:
```
2016-1-16T20:7::9 - info: key reply:  false
Trace
    at null._repeat (/root/node-gdrive-fuse-upload_refactor/src/fs.es6.js:868:25)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
2016-1-16T20:7::9 - info: key reply:  false
Trace
    at null._repeat (/root/node-gdrive-fuse-upload_refactor/src/fs.es6.js:868:25)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
2016-1-16T20:7::9 - debug: retrying read
2016-1-16T20:7::9 - debug: retrying read
Segmentation fault (core dumped)
```

**Comment by wnielson** [comment]
When I got this error, I was running the upload_refactor branch. I switched
back to the master branch and haven't encountered this error since.

**Comment by cal2195** [comment]
I'm currently running the upload_refactor branch, as the master branch wouldn't even work for me!
